Repository decentralized-identity/sidetree, pull requests merged in 2019-06, with the labels that each got.

#230 adding fixes to the blockchain service.
  lib/core/util/SidetreeError.ts
Labels: Bitcoin, bug, high priority

#232 Core service - Fixed bug where first-valid request is formed incorrectly
  lib/core/Blockchain.ts
Labels: bug, high priority

#244 Switching all bcoin specific api calls to generic bitcoin core rpc calls
  lib/bitcoin/BitcoinProcessor.ts
  lib/bitcoin/IBitcoinConfig.ts
  lib/bitcoin/README.md
  lib/bitcoin/setup.sh
  lib/bitcoin/start.sh
  src/bitcoin-config.json
  tests/bitcoin/BitcoinProcessor.spec.ts
Labels: Bitcoin, code refactoring, documentation, enhancement, high priority, mainnet
